### ISSUE TITLE
Fix invalid link

### ISSUE THREAD

**Issue by hiyasw** [yescomment/bh-flaminghydra-ghosttheme#62]
https://www.flaminghydra.com/welcome
why internet do u do this

**Comment by davidmooreppf** [comment]
hunh where does that appear? You can make a Page for Welcome and that would create it... but first, did we link to that supposed page anywhere?

**Comment by unitof** [comment]
Total mystery but now somehow fixed by flipping a bunch of Cloudflare knobs and then flipping them back

**Comment by unitof** [comment]
nvm

**Comment by unitof** [comment]
Fixed with a very annoying Cloudflare rule. https://dash.cloudflare.com/86e1342dd4135beccf9b82bead5def8c/flaminghydra.com/rules/redirect-rules/b718bbf3d38f4249a9fbc263e8a1c87f

![Screenshot 2024-03-07 at 1 21 34 PM](https://github.com/yescomment/bh-flaminghydra-ghosttheme/assets/2448782/6a0bfb84-1171-4a17-a97e-2e9f0d302635)
