### ISSUE TITLE
List of all authors sidebar

### ISSUE THREAD

**Issue by unitof** [yescomment/bh-flaminghydra-ghosttheme#7]
Hoping you can work together to design (Puriya) and then build (Norbert) a reusable list of authors element, which we’ll likely be using in a few pages. Inspiration is in Maria’s sketch here (don’t be literal here with colors/design—we’re sticking with our Dawn theme!).

https://docs.google.com/document/d/1h_Aq55xRiZDKqEU5G5Rga5tZpc097DLxaxeStQ4SPoY/edit
![author-page-mockup](https://github.com/yescomment/bh-flaminghydra-ghosttheme/assets/2448782/42644b79-378e-42e6-8a47-cd21eb61f839)

Defer to you two (and Norbert) if it should be a true sidebar, how it should scroll, where it should pop in mobile, etc.

**Comment by unitof** [comment]
I assigned all authors to Preview Issue so we can test:

https://flaminghydra.com/preview/

And some standalone pieces:

https://flaminghydra.com/author/tom-scocca
https://flaminghydra.com/author/diana-moskovitz/

**Comment by PuriyaMirza** [comment]
Just replying to this email since I’m on my phone—let me know if this
works?

You’re good to do this right now Jacob. I was going to get this done on my
lunch today but I have more to do than expected. I have my entire evening
open and will be working on these designs then as soon as I’m home.



Puriya Mirza  |  Visual Design UI, UX, and Writing   |  www.puriyamirza.com

**Comment by unitof** [comment]
@PuriyaMirza yep! Email replies go to GitHub.

Sounds good, will still want your feedback on what I whip up! But plenty I can do meanwhile.
