### ISSUE TITLE
change homepage to show eight stories and "see more" list of posts

### ISSUE THREAD

**Issue by davidmooreppf** [yescomment/bh-flaminghydra-ghosttheme#77]
The day of homepage layout reckoning is upon us. In Slack messages, Maria writes:

- I think we should have the Latest STORIES be like eight or ten, instead of the most recent four?? 

- Now we've got such a long list of newsletters, the home page is maybe a bit unwieldy (????)

**Comment by unitof** [comment]
Agreed on both. Can play around this week.

**Comment by unitof** [comment]
Added an additional filter to remove `podcast`s from the Recent Stories section, since they looked weird. Might add a *new section* for recent pod eps! Same text-only style as issues. Thoughts?
![36056](https://github.com/yescomment/bh-flaminghydra-ghosttheme/assets/2448782/fb8eb37f-6c33-43f2-8687-36b7a6a3f82f)
